name: under_control_v2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  validators: ^3.0.0
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.11
  dartz: ^0.10.1
  shared_preferences: ^2.0.13
  data_connection_checker_nulls: ^0.0.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  fake_cloud_firestore: ^1.2.2
  firebase_storage: ^10.2.16
  firebase_storage_mocks: ^0.5.0
  smooth_page_indicator: ^1.0.0+2
  circular_bottom_navigation: ^2.0.0
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5
  photo_view: ^0.14.0
  flutter_datetime_picker: ^1.5.1
  mobile_scanner: ^2.0.0
  country_picker: ^2.0.16
  currency_picker: ^2.0.12
  bloc_concurrency: ^0.2.0
  font_awesome_flutter: ^10.2.1
  shimmer: ^2.0.0
  video_player: ^2.4.7
  youtube_player_iframe: ^3.1.0
  file_picker: ^5.2.0+1
  flutter_pdfview: ^1.2.5
  flutter_link_previewer: ^3.1.0
  video_compress: ^3.1.1
  flutter_cache_manager_firebase: ^2.0.1
  vibration: ^1.7.6
  injectable: ^2.1.0
  get_it: ^7.2.0
  collection: ^1.16.0
  flutter_chat_types: ^3.6.0
  flutter_hooks: ^0.18.5+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  bloc_test: ^9.0.3
  build_runner:
  injectable_generator: ^2.1.2
  flutter_lints: ^2.0.1

dependency_overrides:
    firebase_core_platform_interface: 4.5.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/undercontrol.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: "dev_assets/undercontrol-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
