name: under_control_v2
description: User friendly CMMS

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.1+18

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.2
  circular_bottom_navigation: ^2.3.0
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.5
  currency_picker: ^2.0.16
  collection: ^1.17.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.1+1
  file_picker: ^5.3.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.0.0
  firebase_storage_mocks: ^0.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_chat_types: ^3.6.2
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: ^0.19.0
  flutter_link_previewer: ^3.2.2
  flutter_localizations:
    sdk: flutter 
  flutter_local_notifications: ^15.1.0+1
  flutter_pdfview: ^1.3.1
  flutter_speed_dial: ^7.0.0
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  image_picker: ^1.0.0
  injectable: ^2.1.2
  intl: ^0.18.0
  mobile_scanner: ^3.3.0
  photo_view: ^0.14.0
  responsive_framework: ^0.2.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  showcaseview: ^2.0.3
  table_calendar: ^3.0.9
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  validators: ^3.0.0
  vibration: ^1.8.1
  video_compress: ^3.1.2
  video_player: ^2.7.0
  youtube_player_iframe: ^4.0.4
  
dev_dependencies:
  bloc_test: ^9.1.3
  build_runner:
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0

dependency_overrides:
    firebase_core_platform_interface: 4.5.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/undercontrol.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: "dev_assets/undercontrol-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
