import 'package:dartz/dartz.dart';

import '../../../core/error/failures.dart';
import '../../../core/usecases/usecase.dart';
import '../entities/groups_stream.dart';

abstract class GroupRepository {
  ///Gets stream of all groups from the DB.
  ///
  ///Returns [GroupsStream] if operation is successful.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, GroupsStream>> getGroupsStream(String companyId);

  ///Adds new group to the DB.
  ///
  ///Returns [String] containing generated by DB group id.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, String>> addGroup(GroupParams params);

  ///Updates group in the DB.
  ///
  ///Returns [VoidResult] if operation is successful.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, VoidResult>> updateGroup(GroupParams params);

  ///Deletes group from the DB.
  ///
  ///Returns [VoidResult] if operation is successful.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, VoidResult>> deleteGroup(GroupParams params);

  ///Caches groups in local memory.
  ///
  ///Returns [VoidResult] if operation is successful.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, VoidResult>> cacheSelectedGroups(
    SelectedGroupsParams params,
  );

  ///Gets cached groups from local memory.
  ///
  ///Returns [SelectedGroupsParams] containing groups id if found.
  ///Returns [Failure] if operation is unsuccessful.
  Future<Either<Failure, SelectedGroupsParams>> tryToGetCachedgroups();
}
